{% set base_name = "libignition-common" %}
{% set version = "3.7.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-common/archive/ignition-common{{ major_version }}_{{ version }}.tar.gz
    sha256: a09e7dc178c2680751bc27d965991f3abc16b955ab58573a39e30bc3e3d2456e
    patches:
      - fix_test_break.patch
      - librt_linkage.patch  # [linux]
      - framework.patch  # [osx]

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('c') }}    # [not win]
    - vs2017_win-64          # [win64]
    - vs2017_win-32          # [win32]
    - cmake
    - ninja
    - pkgconfig
  host:
    - libignition-math6
    # - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - tinyxml2
  run:
    - libignition-math6
    # - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - tinyxml2

test:
  commands:
    - test -f ${PREFIX}/include/ignition/common{{ major_version }}/ignition/common.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\common{{ major_version }}\ignition\common.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-common
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Common is a component in the ignition framework, a set of libraries designed to rapidly develop robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
