{% set base_name = "libignition-common" %}
{% set version = "4_4.6.1" %}
{% set version_clean = version.split('_')[1] %}
{% set major_version = version.split('_')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_clean }}

source:
  - url: https://github.com/ignitionrobotics/ign-common/archive/ignition-common{{ version }}.tar.gz
    sha256: 97f87bf0fc9cb9505dcc478e751b6900ad654c61aa698e760e5e76b4811dc679
    patches:
      - librt_linkage.patch  # [linux]
      - framework.patch  # [osx]
      - macro_path_binary_relocation.patch
      - fix_ffmpeg6.patch
      - 528.patch

build:
  number: 4
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pkgconfig
  host:
    - libignition-math6
    - libignition-cmake2
    - libignition-utils1
    - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - tinyxml2
    - glib
    - ffmpeg
  run:
    - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - ffmpeg

test:
  commands:
    - test -f ${PREFIX}/include/ignition/common{{ major_version }}/ignition/common.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-common{{ major_version }}-graphics.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-common{{ major_version }}-av.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-common{{ major_version }}-graphics.dylib  # [osx]
    - test -f ${PREFIX}/lib/libignition-common{{ major_version }}-av.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-common{{ major_version }}/ignition-common{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\common{{ major_version }}\ignition\common.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-common{{ major_version }}-graphics.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-common{{ major_version }}-av.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-common{{ major_version }}-graphics.dll (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-common{{ major_version }}-av.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-common{{ major_version }}\\ignition-common{{ major_version }}-config.cmake (exit 0) else (exit 1)  # [win]


about:
  home: https://github.com/ignitionrobotics/ign-common
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Common is a component in the ignition framework, a set of libraries designed to rapidly develop robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
    - traversaro
