{% set base_name = "libignition-common" %}
{% set version = "3.15.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/gz-common/archive/ignition-common{{ major_version }}_{{ version }}.tar.gz
    sha256: fc1bf79eb53e3b56b4b8e0eb6965ec68982da18ea42154dd4fd891ac739d65fb
    patches:
      - librt_linkage.patch  # [linux]
      - framework.patch  # [osx]
      - fix_test_break.patch
      - fix_ffmpeg6.patch
      - 501.patch
      - 517.patch

build:
  number: 5
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pkgconfig
  host:
    - libignition-math6
    - libignition-cmake2
    - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - tinyxml2
    - glib
    - ffmpeg
  run:
    - dlfcn-win32  # [win]
    - libuuid      # [linux]
    - freeimage
    - gts
    - ffmpeg

test:
  commands:
    - test -f ${PREFIX}/include/ignition/common{{ major_version }}/ignition/common.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\common{{ major_version }}\ignition\common.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-common
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Common is a component in the ignition framework, a set of libraries designed to rapidly develop robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
